// Code generated by genny. DO NOT EDIT.
// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/tehbilly/genny

//go:build (x && y) || z
// +build x,y z

package buildtags

import (
	"fmt"
)

func intPrint(t int) {
	fmt.Println(t)
}
